In [3]:
import numpy as np
import pandas as pd

In [7]:
df=pd.read_csv("sales_returns.csv")
df

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,cust_age,cust_gender,segment,country,...,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,returned
0,CA-2015-143336,27/08/15,01/09/15,Second Class,ZD-21925,Zuschuss Donatelli,19,Female,Consumer,United States,...,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824,True
1,CA-2015-143336,27/08/15,01/09/15,Second Class,ZD-21925,Zuschuss Donatelli,19,Female,Consumer,United States,...,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110,True
2,CA-2015-143336,27/08/15,01/09/15,Second Class,ZD-21925,Zuschuss Donatelli,19,Female,Consumer,United States,...,West,OFF-BI-10002215,Office Supplies,Binders,"Wilson Jones Hanging View Binder, White, 1""",22.720,4,0.2,7.3840,True
3,CA-2017-111682,17/06/17,18/06/17,First Class,TB-21055,Ted Butterfield,20,Female,Consumer,United States,...,East,OFF-ST-10000604,Office Supplies,Storage,Home/Office Personal File Carts,208.560,6,0.0,52.1400,True
4,CA-2017-111682,17/06/17,18/06/17,First Class,TB-21055,Ted Butterfield,20,Female,Consumer,United States,...,East,OFF-PA-10001569,Office Supplies,Paper,Xerox 232,32.400,5,0.0,15.5520,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,US-2015-143287,11/11/15,17/11/15,Standard Class,KN-16705,Kristina Nunn,19,Female,Home Office,United States,...,East,OFF-PA-10004039,Office Supplies,Paper,Xerox 1882,223.920,4,0.0,109.7208,True
1298,US-2015-143287,11/11/15,17/11/15,Standard Class,KN-16705,Kristina Nunn,24,Male,Home Office,United States,...,East,OFF-SU-10001574,Office Supplies,Supplies,Acme Value Line Scissors,7.300,2,0.0,2.1900,True
1299,CA-2018-121258,26/02/18,03/03/18,Standard Class,DB-13060,Dave Brooks,21,Female,Consumer,United States,...,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332,True
1300,CA-2018-121258,26/02/18,03/03/18,Standard Class,DB-13060,Dave Brooks,23,Female,Consumer,United States,...,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932,True
1301,CA-2018-121258,26/02/18,03/03/18,Standard Class,DB-13060,Dave Brooks,21,Female,Consumer,United States,...,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200,True

In [8]:
#in this data sets there are 1302 rows and 23 columns

In [13]:
df=pd.read_excel("sample_superstore.xls")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [14]:
#here we can find 9994 rows and 21 columns.

In [16]:
df=pd.read_json("countries.json")
df

,id,name,iso3,iso2,numeric_code,phone_code,capital,currency,currency_name,currency_symbol,tld,native,region,subregion,timezones,translations,latitude,longitude,emoji,emojiU
0,1,Afghanistan,AFG,AF,4,93,Kabul,AFN,Afghan afghani,؋,.af,افغانستان,Asia,Southern Asia,"[{'zoneName': 'Asia/Kabul', 'gmtOffset': 16200...","{'kr': '아프가니스탄', 'pt-BR': 'Afeganistão', 'pt':...",33.000000,65.0,🇦🇫,U+1F1E6 U+1F1EB
1,2,Aland Islands,ALA,AX,248,+358-18,Mariehamn,EUR,Euro,€,.ax,Åland,Europe,Northern Europe,"[{'zoneName': 'Europe/Mariehamn', 'gmtOffset':...","{'kr': '올란드 제도', 'pt-BR': 'Ilhas de Aland', 'p...",60.116667,19.9,🇦🇽,U+1F1E6 U+1F1FD
2,3,Albania,ALB,AL,8,355,Tirana,ALL,Albanian lek,Lek,.al,Shqipëria,Europe,Southern Europe,"[{'zoneName': 'Europe/Tirane', 'gmtOffset': 36...","{'kr': '알바니아', 'pt-BR': 'Albânia', 'pt': 'Albâ...",41.000000,20.0,🇦🇱,U+1F1E6 U+1F1F1
3,4,Algeria,DZA,DZ,12,213,Algiers,DZD,Algerian dinar,دج,.dz,الجزائر,Africa,Northern Africa,"[{'zoneName': 'Africa/Algiers', 'gmtOffset': 3...","{'kr': '알제리', 'pt-BR': 'Argélia', 'pt': 'Argél...",28.000000,3.0,🇩🇿,U+1F1E9 U+1F1FF
4,5,American Samoa,ASM,AS,16,+1-684,Pago Pago,USD,US Dollar,$,.as,American Samoa,Oceania,Polynesia,"[{'zoneName': 'Pacific/Pago_Pago', 'gmtOffset'...","{'kr': '아메리칸사모아', 'pt-BR': 'Samoa Americana', ...",-14.333333,-170.0,🇦🇸,U+1F1E6 U+1F1F8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,243,Wallis And Futuna Islands,WLF,WF,876,681,Mata Utu,XPF,CFP franc,₣,.wf,Wallis et Futuna,Oceania,Polynesia,"[{'zoneName': 'Pacific/Wallis', 'gmtOffset': 4...","{'kr': '왈리스 푸투나', 'pt-BR': 'Wallis e Futuna', ...",-13.300000,-176.2,🇼🇫,U+1F1FC U+1F1EB
246,244,Western Sahara,ESH,EH,732,212,El-Aaiun,MAD,Moroccan Dirham,MAD,.eh,الصحراء الغربية,Africa,Northern Africa,"[{'zoneName': 'Africa/El_Aaiun', 'gmtOffset': ...","{'kr': '서사하라', 'pt-BR': 'Saara Ocidental', 'pt...",24.500000,-13.0,🇪🇭,U+1F1EA U+1F1ED
247,245,Yemen,YEM,YE,887,967,Sanaa,YER,Yemeni rial,﷼,.ye,اليَمَن,Asia,Western Asia,"[{'zoneName': 'Asia/Aden', 'gmtOffset': 10800,...","{'kr': '예멘', 'pt-BR': 'Iêmen', 'pt': 'Iémen', ...",15.000000,48.0,🇾🇪,U+1F1FE U+1F1EA
248,246,Zambia,ZMB,ZM,894,260,Lusaka,ZMW,Zambian kwacha,ZK,.zm,Zambia,Africa,Eastern Africa,"[{'zoneName': 'Africa/Lusaka', 'gmtOffset': 72...","{'kr': '잠비아', 'pt-BR': 'Zâmbia', 'pt': 'Zâmbia...",-15.000000,30.0,🇿🇲,U+1F1FF U+1F1F2
249,247,Zimbabwe,ZWE,ZW,716,263,Harare,ZWL,Zimbabwe Dollar,$,.zw,Zimbabwe,Africa,Eastern Africa,"[{'zoneName': 'Africa/Harare', 'gmtOffset': 72...","{'kr': '짐바브웨', 'pt-BR': 'Zimbabwe', 'pt': 'Zim...",-20.000000,30.0,🇿🇼,U+1F1FF U+1F1FC

In [ ]:
pd.read_csv("sales_returns.csv",)